### ISSUE TITLE
Mac编译问题

### ISSUE THREAD

**Issue by marvin-min** [qibin0506/Meizar#1]
/usr/local/go/pkg/tool/darwin_amd64/link: cannot open file /usr/local/go/pkg/darwin_amd64/github.com/PuerkitoBio/goquery.a: open /usr/local/go/pkg/darwin_amd64/github.com/PuerkitoBio/goquery.a: no such file or directory

**Comment by qibin0506** [comment]
项目依赖：goquery
你需要使用先：go get github.com/PuerkitoBio/goquery

**Comment by marvin-min** [comment]
搞定了。应该是环境变量的问题。zsh path丢失的问题
